### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Tonio31** [Quobject/aws-cli-js#6]
Hello,

I'm trying to run the following command:

```
aws.command( 's3 sync ./countries/belize s3://cdn.***.org/countries/belize' )
  .then( ( data ) => {
    const test = JSON.stringify( data );
    console.log( 'test=', test );
    console.log( 'data = ', data );
  } );
```

And I receive an error on "console.log( 'data = ', data );", this is the output I get:

```
test= {"command":"aws s3 sync ./countries/belize s3://cdn.letspack.org/countries/belize","error":"","object":{},"raw":""}
data =  { command:
   'aws s3 sync ./countries/belize s3://cdn.***.org/countries/belize',
  error: '',
  object:
   SyntaxError: Unexpected end of JSON input
       at JSON.parse (<anonymous>)
       at extractResult (/Users/***/DEV/letspack/scripts.cdn.***.org/node_modules/aws-cli-js/lib/index.js:11:30)
       at Promise.resolve.then.then (/Users/***/DEV/letspack/scripts.cdn.***.org/node_modules/aws-cli-js/lib/index.js:74:20),
  raw: '' }
```

I tried using --output json like described in [this issue](https://github.com/Quobject/aws-cli-js/issues/4) but it didn't change anything:

```
test= {"command":"aws s3 sync ./countries/belize s3://cdn.***.org/countries/belize --output json","error":"","object":{},"raw":""}
data =  { command:
   'aws s3 sync ./countries/belize s3://cdn.***.org/countries/belize --output json',
  error: '',
  object:
   SyntaxError: Unexpected end of JSON input
       at JSON.parse (<anonymous>)
       at extractResult (/Users/***/DEV/letspack/scripts.cdn.***.org/node_modules/aws-cli-js/lib/index.js:11:30)
       at Promise.resolve.then.then (/Users/***/DEV/letspack/scripts.cdn.***.org/node_modules/aws-cli-js/lib/index.js:74:20),
  raw: '' }
```

I'm probably doing something wrong but I can't figure out what

**Comment by mattqs** [comment]
from the source code:
https://github.com/Quobject/aws-cli-js/blob/master/src/index.ts lines 10 - 14
```
  try {
    result.object = JSON.parse(result.raw);
  } catch (e) {
    result.object = e;
  }
```

Your ```result.raw``` is empty string and JSON.parse throws exception, which is in result.object.

You can ignore result.object if result.raw is empty.
